{
 "title": "KOREK Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_value",
     "query": "SELECT last(\"value\") FROM \"cpu_value\" WHERE (\"type\" = 'percent' AND \"type_instance\" = 'user') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "user" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 6, "x": 5, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "free" }
     ]
    },
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" }
     ]
    },
    {
     "alias": "reserved",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "reserved" }
     ]
    }
   ]
  },
  {
   "title": "Accepted Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "accepted",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_value",
     "query": "SELECT DERIVATIVE(\"value\")*10 FROM \"nginx_value\" WHERE  \"type_instance\" = 'accepted'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "accepted" }
     ]
    }
   ]
  },
  {
   "title": "Requests Handled",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "alias": "handled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_value",
     "query": "SELECT DERIVATIVE(\"value\")*10 FROM \"nginx_value\" WHERE \"type_instance\" = 'handled'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "ed5accc944aa" }
     ]
    }
   ]
  },
  {
   "title": "System RAM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "memory_value",
     "query": "SELECT last(\"value\") FROM \"memory_value\" WHERE (\"type\" = 'percent' AND \"type_instance\" = 'used') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "percent" },
      { "condition": "AND", "key": "type_instance", "operator": "=", "value": "used" }
     ]
    }
   ]
  },
  {
   "title": "Application RAM",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "SELECT last(\"value\") FROM \"memory_value\" WHERE (\"type_instance\" = 'free')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "free" }
     ]
    },
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "SELECT last(\"value\") FROM \"memory_value\" WHERE (\"type_instance\" = 'used')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "used" }
     ]
    },
    {
     "alias": "cache",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_value",
     "query": "SELECT last(\"value\") FROM \"memory_value\" WHERE (\"type_instance\" = 'cached')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "cached" }
     ]
    }
   ]
  },
  {
   "title": "Server Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "reading",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_value",
     "query": "SELECT mean(\"value\") FROM \"nginx_value\" WHERE (\"type_instance\" = 'reading') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "reading" }
     ]
    },
    {
     "alias": "waiting",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "waiting" }
     ]
    },
    {
     "alias": "writing",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "writing" }
     ]
    },
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "active" }
     ]
    }
   ]
  },
  {
   "title": "200 Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "200 Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_value",
     "query": "SELECT last(\"value\") FROM \"tail_value\" WHERE (\"type_instance\" = 'http_2xx')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "http_2xx" }
     ]
    }
   ]
  },
  {
   "title": "500 Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "200 Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_value",
     "query": "SELECT last(\"value\") FROM \"tail_value\" WHERE (\"type_instance\" = 'http_5xx')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "http_2xx" }
     ]
    }
   ]
  },
  {
   "title": "400 Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "200 Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_value",
     "query": "SELECT last(\"value\") FROM \"tail_value\" WHERE (\"type_instance\" = 'http_4xx')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "http_2xx" }
     ]
    }
   ]
  },
  {
   "title": "300 Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "200 Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail_value",
     "query": "SELECT last(\"value\") FROM \"tail_value\" WHERE (\"type_instance\" = 'http_3xx')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type_instance", "operator": "=", "value": "http_2xx" }
     ]
    }
   ]
  },
  {
   "title": "PostGreSQL metrics",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT relid,schemaname,relname,seq_scan,seq_tup_read,idx_scan,idx_tup_fetch,n_tup_ins,n_tup_upd,n_tup_del,n_tup_hot_upd,n_live_tup,n_dead_tup\nFROM pg_stat_all_tables WHERE relname LIKE 'korek%' or relname LIKE 'auth%'"
    }
   ]
  },
  {
   "title": "Nginx logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nginx_logs",
     "query": "SELECT time,log,value FROM \"nginx_logs\"",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select  \nusename as \"User\", \napplication_name as \"App\", \nclient_addr as \"IP\", \nto_char(backend_start, 'YYYY-MM-DD HH24:MI:SS') as \"TimeConnect\", \nto_char(query_start, 'YYYY-MM-DD HH24:MI:SS') as \"TimeQuery\", \nto_char(state_change, 'YYYY-MM-DD HH24:MI:SS') as \"TimeState\", \nstate,\nquery as \"Query\"\nfrom pg_stat_activity \nwhere pid <> pg_backend_pid()\nAND query not like '%pg_%' AND query not like '%migrations%'\norder by backend_start;"
    }
   ]
  }
 ]
}