# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=False, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=False, max_length=1000)),
                ('barcode', models.IntegerField(blank=False)),
                ('brand', models.CharField(blank=False, default='', max_length=100)),
                ('language', models.CharField(default='fr', max_length=2)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products-image', to='knap.Product')),
                ('image', models.ImageField(blank=True, upload_to="Products_Image/", default="")),
           ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
