# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Product',
            name='language',
            field=models.TextField(choices=[('fr', 'FR'),('en', 'EN')], default='fr', max_length=100),
        ),
    ]
